---
title: "Brady Campain Scorecard Effectiveness"
output: 
  html_document: 
    self_contained: no
---

Just the data. Draw your own conclusions.

```{r rawdata, echo=FALSE, message=FALSE, warning=FALSE}
d <- read.csv(
text = "
\"state\",brady_raw_score,murders,murders_with_firearms,active_shooter_deaths,population
\"Alabama\",3.5,2,1,17,4830533
\"Alaska\",‐7,34,12,0,737442
\"Arizona\",‐8,304,184,8,6630799
\"Arkansas\",1,154,110,1,2957957
\"California\",75,1745,1224,45,38414128
\"Colorado\",14.5,174,88,23,5271132
\"Connecticut\",70,86,60,35,3597168
\"Delaware\",34.5,39,33,0,925353
\"Florida\",3,,,29,19594467
\"Georgia\",2,534,411,3,9991562
\"Hawaii\",58.5,9,6,0,1408765
\"Idaho\",0,26,15,1,1612785
\"Illinois\",45,433,364,15,12889580
\"Indiana\",4.5,311,238,5,6570518
\"Iowa\",14,42,18,0,3092224
\"Kansas\",‐4,112,78,6,2894630
\"Kentucky\",‐3.5,165,111,5,4398500
\"Louisiana\",‐2,453,356,6,4627491
\"Maine\",3,24,12,0,1328778
\"Maryland\",66.5,379,268,0,5936040
\"Massachusetts\",60.5,135,78,0,6708810
\"Michigan\",15,625,440,2,9900506
\"Minnesota\",19.5,110,60,17,5420541
\"Mississippi\",‐4,142,110,6,2990976
\"Missouri\",‐0.5,371,273,14,6043708
\"Montana\",‐3,15,9,0,1014402
\"Nebraska\",6.5,57,39,9,1869300
\"Nevada\",1.5,157,87,7,2790366
\"New Hampshire\",5.5,21,5,0,1322660
\"New Jersey\",68.5,401,291,2,8907384
\"New Mexico\",0,106,59,4,2086890
\"New York\",65.5,648,362,18,19691032
\"North Carolina\",1.5,452,315,5,9845432
\"North Dakota\",2,11,4,0,723626
\"Ohio\",10,434,309,18,11572232
\"Oklahoma\",1,191,127,0,3853405
\"Oregon\",11,78,43,5,3928030
\"Pennsylvania\",20,594,440,25,12783536
\"Rhode Island\",41.5,31,18,0,1052856
\"South Carolina\",1,296,224,1,4768498
\"South Dakota\",‐4.5,12,3,0,845270
\"Tennessee\",2,327,223,4,6496130
\"Texas\",1.5,1133,760,21,26500674
\"Utah\",‐2,49,31,5,2903685
\"Vermont\",‐4,9,5,2,627129
\"Virginia\",7,315,225,35,8267875
\"Washington\",19.5,155,86,26,6973281
\"West Virginia\",3,54,30,0,1852985
\"Wisconsin\",13,157,103,29,5743653
\"Wyoming\",‐5,15,9,0,583131
")
d$brady_raw_score <- as.numeric(d$brady_raw_score)
d$murders_per_100000 <- 100000 * d$murders / d$population
d$firearm_murders_per_100000 <- d$murders_with_firearms / (d$population/100000)
d$active_shooter_deaths_per_100000 <- d$active_shooter_deaths / (d$population*(2013-2000+1)/100000)
```

```{r scatterplot1,  echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=5, dpi=300}
par(mar=c(4,4,1,1))
symbols(d$brady_raw_score, d$firearm_murders_per_100000, 
     circles=sqrt(d$population), 
  	 xlab="Brady raw score", 
     ylab="Murders with firearm per 100,000",
     fg="white", bg="yellow", inches=0.2
     )
text(d$brady_raw_score, d$firearm_murders_per_100000, d$state, cex=0.5)
```

```{r a1m2, echo=FALSE, message=FALSE, warning=FALSE, comment=NA}
summary(lm(d$firearm_murders_per_100000~d$brady_raw_score, weights=d$population))
```

```{r scatterplot2,  echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=5, dpi=300}
par(mar=c(4,4,1,1))
symbols(d$brady_raw_score, d$active_shooter_deaths_per_100000, 
     circles=sqrt(d$population), 
  	 xlab="Brady raw score", 
     ylab="Deaths in active shooter incidents per 100,000",
     fg="white", bg="lightblue", inches=0.2
     )
text(d$brady_raw_score, d$active_shooter_deaths_per_100000, d$state, cex=0.5)
```

```{r a2m1, echo=FALSE, message=FALSE, warning=FALSE, comment=NA}
summary(lm(d$active_shooter_deaths_per_100000~d$brady_raw_score, weights=d$population))
```

Sources
-------

* Brady Campain to Prevent Gun Violence,
  [2013 State Scorecard](http://www.bradycampaign.org/2013-state-scorecard)

* FBI, [Murder by State, Types of Weapons, 2013](https://www.fbi.gov/about-us/cjis/ucr/crime-in-the-u.s/2013/crime-in-the-u.s.-2013/tables/table-20/table_20_murder_by_state_types_of_weapons_2013.xls)

* United States Census Bureau, [Population Estimates](http://www.census.gov/popest/data/state/totals/2015/index.html)
  
* FBI, [A Study of Active Shooter Incidents in the United States Between 2000 and 2013](https://www.fbi.gov/news/stories/2014/september/fbi-releases-study-on-active-shooter-incidents/pdfs/a-study-of-active-shooter-incidents-in-the-u.s.-between-2000-and-2013)
  
Data
----

```{r d, echo=FALSE, message=FALSE, warning=FALSE, comment=NA}
d$murders_per_100000 <- NULL
d$firearm_murders_per_100000 <- NULL
d$active_shooter_deaths_per_100000 <- NULL
options(scipen=999)
options(width=200)
d
```

Source Code
-----------

[http://github.com/brady-score](http://github.com/brady-score)
